# Generated by Django 2.2.7 on 2020-08-28 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import votie.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matric_no', models.CharField(max_length=30, unique=True, verbose_name='Matric Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('faculty', models.CharField(choices=[('Faculty of science', 'Faculty of science'), ('Faculty of education', 'Faculty of education'), ('Faculty of law', 'Faculty of law'), ('Faculty of agric', 'Faculty of agric'), ('Faculty of arts', 'Faculty of arts')], max_length=30, null=True)),
                ('Department', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_voter', models.BooleanField(default=False, verbose_name='voter')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', votie.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('choie_image', models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='choice_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=202)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votie.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votie.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votie.Poll'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('faculty', models.CharField(choices=[('Faculty of science', 'Faculty of science'), ('Faculty of education', 'Faculty of education'), ('Faculty of law', 'Faculty of law'), ('Faculty of agric', 'Faculty of agric'), ('Faculty of arts', 'Faculty of arts')], max_length=30, null=True)),
                ('Department', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='images.jpeg', null=True, upload_to='candidates_info/')),
                ('description', models.CharField(max_length=255)),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votie.Position')),
            ],
        ),
    ]
